% Test bench script for 'Granulator_plugin'.
% Generated by Audio Test Bench on 29-Dec-2022 20:16:23 UTC+01:00.

% Create test bench input and output
deviceReader = audioDeviceReader('Device','Primary Sound Capture Driver', ...
    'NumChannels',2);
deviceWriter = audioDeviceWriter('SampleRate',deviceReader.SampleRate);

% Set up the system under test
sut = Granulator_plugin;
setSampleRate(sut,deviceReader.SampleRate);

% Open parameterTuner for interactive tuning during simulation
tuner = parameterTuner(sut);
drawnow

% Stream processing loop
nOverruns = 0;
nUnderruns = 0;
maxIterations = 10000000;
for iter = 1:maxIterations
    % Read from input, process, and write to output
    [in,novr] = deviceReader();
    nOverruns = nOverruns + novr;   % Increment the overrun counter
    out = process(sut,in);
    nUnderruns = nUnderruns + deviceWriter(out);
    
    % Process parameterTuner callbacks
    drawnow limitrate
end

% Clean up
release(deviceReader)
release(deviceWriter)

